Clean up env vars and x startup

diff --git a/.local/bin/scripts/tui/detemplate b/.local/bin/scripts/tui/detemplate
--- a/.local/bin/scripts/tui/detemplate
+++ b/.local/bin/scripts/tui/detemplate
@@ -1,9 +1,12 @@
 #!/bin/sh
 
+[ -f $XDG_CONFIG_HOME/colorrc ] && source $XDG_CONFIG_HOME/colorrc
+
 if [ -f "$1" ] && [[ "$1" == *"template."* ]]; then
   filename=$(basename "$1" | sed -E 's/^template\.//')
   output="$(dirname "$1")/$filename"
   envsubst < $1 > $output
 else
-  echo "template does not exist, or file name is invalid."
+  echo -e "${RED}template file does not exist or file name \"$1\" is invalid.${NC}"
+  exit 1
 fi
