Add doas to FreeBSD
/dev/dri/card0 doesn't seem to be detected in 12.2-RELEASE, although it could just be me not understanding video drivers

diff --git a/.local/bin/tui/sbuild b/.local/bin/tui/sbuild
--- a/.local/bin/tui/sbuild
+++ b/.local/bin/tui/sbuild
@@ -1,14 +1,20 @@
 #!/bin/sh
 # builds a given suckless utility using template files
 
-dir=$XDG_CONFIG_HOME/$1
+dir="${XDG_CONFIG_HOME}/${1}"
 
-[ -z $1 ] && \
-  echo -e "${RED}No suckless utility specified.${NC}" && exit 1
-[ ! -d $dir ] && \
-  echo -e "${RED}Invalid suckless utility.${NC}" && exit 1
+[ -z "${1}" ] && \
+  echo "${RED}No suckless utility specified.${NC}" && exit 1
+[ ! -d "${dir}" ] && \
+  echo "${RED}Invalid suckless utility.${NC}" && exit 1
 
-olddir=$(pwd)
-cd $dir
-$DETEMPLATE template.config.h && sudo make clean install
-cd $olddir
+olddir="$(pwd)"
+cd "${dir}"
+
+$DETEMPLATE "template.config.h"
+case "${OS}" in
+  "${OS_FREEBSD}") doas make clean install ;;
+  *) sudo make clean install ;;
+esac
+
+cd "${olddir}"
